### ISSUE TITLE
Arranging the rows and columns of the heat map

### ISSUE THREAD

**Issue by Chhiring-Lama** [obigriffith/biostar-tutorials#7]
Hi, 

I am using heatmap.3() to plot a graph. Even though I use scale = "none" and dendrogram = "none". It is automatically reordering them. I understand this has something to do with the hclustfun. I cannot plot without providing a value for the parameter. Do you know how I can define the hclust() function such that I keeps the original ordering of the cells. 

Thanks!

**Comment by obigriffith** [comment]
Check out the parameters Rowv and Colv. If you set one or both of these to FALSE then no dendrogram will be computed and no reordering performed for rows and/or columns.

**Comment by Chhiring-Lama** [comment]
That was very helpful, thank you!
